DROP SCHEMA PUBLIC CASCADE;

CREATE TABLE users (
  id INTEGER IDENTITY PRIMARY KEY,
  username VARCHAR(30) UNIQUE,
  password VARCHAR(10),
  );

CREATE TABLE expense (
  id INTEGER IDENTITY PRIMARY KEY,
  amount DOUBLE ,
  date TIMESTAMP ,
  description VARCHAR(30),
  accountId INTEGER NOT NULL

);

ALTER TABLE expense ADD FOREIGN KEY (accountId) REFERENCES users (id);
